version: '3'
services:
  web:
    build: ./docker/web
    ports:
      - "8080:80"
      - "1443:443"
    volumes:
      - ./docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/key/etc/ssl/certs/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./docker/key/etc/ssl/private/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./janus:/var/www/html
  janus-gateway:
    build: ./docker/janus
    command: ["/usr/local/bin/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    depends_on:
      - web
    volumes:
      - ./docker/janus/etc/janus/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg
      - ./docker/key/etc/ssl/certs/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./docker/key/etc/ssl/private/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ./janus:/var/www/html
    working_dir: /var/www/html
    tty: true
